# Generated by Django 3.1.7 on 2021-04-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210407_1926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Admin_var',
        ),
        migrations.AlterModelOptions(
            name='admin_var',
            options={},
        ),
    ]
